[project]
name = "fractal-generator"
version = "0.1.0"
description = "This program use assebly and python to create fractal genarator."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.1",
    "numpy>=2.2.4",
]
